### ISSUE TITLE
Improvement in Card Design

### ISSUE THREAD

**Issue by Kushagra-Kukreti** [Kushagra-Kukreti/Video-Streamer-App#3]
Card Structure can be better as it looks little bit unorganised

Attached is the sample:

![Screenshot 2024-01-17 003818](https://github.com/Kushagra-Kukreti/Video-Streamer-App/assets/102087385/ffc566dd-5f7d-4ef6-93bc-2525dcd810f8)

**Comment by zablon-oigo** [comment]
Hello, Is the issue still open, I would like to tackle it.
 are you using any CSS Framework or just Vanilla CSS?
 Plus If you have a particular design in mind pls share

**Comment by zablon-oigo** [comment]
Alright that can be done , Please assign me the issue

**Comment by Kushagra-Kukreti** [comment]
Done from my side. Feel free to ask anything.

**Comment by zablon-oigo** [comment]
Hey , I have gone through your project but I couldn't see any video card ...
Before I assume I wanted to ask if the file **video.tsx** is the one I am supposed to edit right? 
![landin](https://github.com/Kushagra-Kukreti/Video-Streamer-App/assets/143833326/ac70a3f9-48a3-4ce6-9146-01293fbf65ce)

**Comment by Kushagra-Kukreti** [comment]
Keep it dark only because sometimes video thumbnail might be red , just do bottom  and right '0.5rem' it would be better

**Comment by zablon-oigo** [comment]
![card 3](https://github.com/Kushagra-Kukreti/Video-Streamer-App/assets/143833326/7f007e04-2f27-4a27-8992-8ab725313cb2)

how about now ?

**Comment by Kushagra-Kukreti** [comment]
It looks fine.
